import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:dragger_survey/src/services/services.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:dragger_survey/src/blocs/blocs.dart';
import 'package:dragger_survey/src/widgets/select_granularity.dart';

class SurveySetForm extends StatefulWidget {
  @override
  _SurveySetFormState createState() => _SurveySetFormState();
}

class _SurveySetFormState extends State<SurveySetForm> {
  final _formKey = GlobalKey<FormState>();
  bool _formHasChanged = false;

  // autogenerated
  String _id;

  // required
  DateTime _created = DateTime.now().toUtc();
  String _name;
  int _resolution;
  String _xName;
  String _yName;

  // Optional
  String _description = "";
  String _xDescription = "";
  String _yDescription = "";
  dynamic _prismSurveys = [];

  // When edited
  DateTime _edited;

  @override
  Widget build(BuildContext context) {
    final PrismSurveySetBloc prismSurveySetBloc =
        Provider.of<PrismSurveySetBloc>(context);

    return Form(
      key: _formKey,
      onChanged: () {
        if (_formKey.currentState.validate()) {
          setState(() {
            _formHasChanged = true;
          });
        }
      },
      child: buildForm(
          bloc: prismSurveySetBloc, context: context, formKey: _formKey),
    );
  }

  Widget buildForm({@required bloc, @required context, @required formKey}) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget>[
        TextFormField(
          textInputAction: TextInputAction.next,
          keyboardType: TextInputType.text,
          decoration: InputDecoration(
            labelText: "Survey Name",
            hintText: "Please provide a meaningful name",
          ),
          // initialValue: attribute,
          validator: (value) {
            if (value.isEmpty) {
              return 'Please enter a name';
            }
            return null;
          },
          onSaved: (value) => _name = value,
        ),
        TextFormField(
          textInputAction: TextInputAction.next,
          keyboardType: TextInputType.text,
          decoration: InputDecoration(
            labelText: "Survey set description",
            hintText: "The description of the prism survey",
          ),
          // initialValue: attribute,
          onSaved: (value) => _description = value,
        ),
        SelectGranularity(),
        TextFormField(
          textInputAction: TextInputAction.next,
          keyboardType: TextInputType.text,
          decoration: InputDecoration(
            labelText: "Label for x-axis",
            hintText: "Should be easy to understand",
          ),
          // initialValue: attribute,
          validator: (value) {
            if (value.isEmpty) {
              return 'Please enter a label';
            }
            return null;
          },
          onSaved: (value) => _xName = value,
        ),
        TextFormField(
          textInputAction: TextInputAction.next,
          keyboardType: TextInputType.text,
          decoration: InputDecoration(
            labelText: "X-axis desciption",
            hintText: "What does the x-axis stand for",
          ),
          // initialValue: attribute,
          onSaved: (value) => _xDescription = value,
        ),
        TextFormField(
          textInputAction: TextInputAction.next,
          keyboardType: TextInputType.text,
          decoration: InputDecoration(
            labelText: "Label for y-axis",
            hintText: "Should be easy to understand",
          ),
          // initialValue: attribute,
          validator: (value) {
            if (value.isEmpty) {
              return 'Please enter a label';
            }
            return null;
          },
          onSaved: (value) => _yName = value,
        ),
        TextFormField(
          textInputAction: TextInputAction.next,
          keyboardType: TextInputType.text,
          decoration: InputDecoration(
            labelText: "Y-axis desciption",
            hintText: "What does the y-axis stand for",
          ),
          // initialValue: attribute,
          onSaved: (value) => _yDescription = value,
        ),

        
        buildSubmitButton(
          bloc: bloc,
          context: context,
          formKey: formKey,
        ),
      ],
    );
  }

  Widget buildSubmitButton(
      {@required bloc, @required context, @required formKey}) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 8.0),
      child: SizedBox(
        width: double.infinity,
        child: RaisedButton(
          disabledColor: Colors.orange.shade50,
          shape:
              RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
          color: Colors.orange,
          textColor: Colors.white,
          onPressed: _formHasChanged
              ? () {
                  _buttonOnPressed(formKey: formKey, bloc: bloc);
                  print("Submit button presssed");
                  Navigator.of(context).pop();
                }
              : null,
          child: Text('Submit'),
        ),
      ),
    );
  }

  void _sendFormValuesToBloc({@required PrismSurveySetBloc bloc}) {
    Map<String, dynamic> surveySet = {
      "created": _created,
      "name": _name,
      "description": _description,
      "resolution": _resolution,
      "xName": _xName,
      "xDescription": _xDescription,
      "yName": _yName,
      "yDescription": _yDescription,
    };
    print("===============================");
    print("Values sent to bloc:");
    print("_created: $_created");
    print("_name: $_name");
    print("_description: $_description");
    print("_resolution: $_resolution");
    print("_xName: $_xName");
    print("_xDescription: $_xDescription");
    print("_yName: $_yName");
    print("_yDescription: $_yDescription");
    print("================================");

    bloc.addPrismSurveySetToDb(surveySet: surveySet);
    print("2) ----> Form values have been sent to bloc");
  }

  void _buttonOnPressed({formKey, @required bloc}) {
    if (formKey.currentState.validate()) {
      print("1a) ----> Form has been validated.");
      formKey.currentState.save();

      _sendFormValuesToBloc(bloc: bloc);
      print("1b) ----> Sending form values to bloc.");

      print("1c) ----> Sent data:");
      print("_created: $_created");
      print("_name: $_name");
      print("_description: $_description");
      print("_resolution: $_resolution");
      print("_xName: $_xName");
      print("_yName: $_yName");
      print("_xDescription: $_xDescription");
      print("_xDescription: $_xDescription");
      print("_yDescription: $_yDescription");
    }
  }
}
